### ISSUE TITLE
Project Scope Approval 

### ISSUE THREAD

**Issue by luczaki114** [wdi-no-idea/DOTA2-Counter-Picker#1]
Required: Have instructors approve the scope of the project.

Project name: Dota 2 Counter-Picker
Possible wireframes:
Features:

**Comment by code-for-coffee** [comment]
@myjohnson23 @luczaki114 this is awesome. I'm not a huge MOBA player but I think you should market this as much as you can to newbie players. You'll knock it out of the park with the Mechanize library! 

Approved!
